USE TestDB

INSERT INTO Categories (Name) VALUES ('Информационные технологии')
INSERT INTO Categories (Name) VALUES ('Спорт')
INSERT INTO Categories (Name) VALUES ('География')
INSERT INTO Categories (Name) VALUES ('История')

INSERT INTO Tests (Name, Rate, Timer, CategoryId) VALUES ('Устройство компьютера', 75, 10, 1)
INSERT INTO Tests (Name, Rate, Timer, CategoryId) VALUES ('Язык программирования C#', 80, 5, 1)
INSERT INTO Tests (Name, Rate, Timer, CategoryId) VALUES ('Олимпийские игры', 70, 4, 2)
INSERT INTO Tests (Name, Rate, Timer, CategoryId) VALUES ('Футбол', 70, NULL, 2)
INSERT INTO Tests (Name, Rate, Timer, CategoryId) VALUES ('Столицы', 70, 1, 3)
INSERT INTO Tests (Name, Rate, Timer, CategoryId) VALUES ('Великая Отечественная Война', 70, 15, 4)

INSERT INTO Questions (Name, TestId, IsOpenType) VALUES ('Что такое компьютер?', 1, 'False')
INSERT INTO Questions (Name, TestId, IsOpenType) VALUES ('Устройством чего является манипулятор “мышь”?', 1, 'False')
INSERT INTO Questions (Name, TestId, IsOpenType) VALUES ('Что значит адресуемость оперативной памяти?', 1, 'False')
INSERT INTO Questions (Name, TestId, IsOpenType) VALUES ('Что хранится в ячейках оперативной памяти?', 1, 'False')
INSERT INTO Questions (Name, TestId, IsOpenType) VALUES ('Что такое клавиатура ?', 1, 'False')
INSERT INTO Questions (Name, TestId, IsOpenType) VALUES ('Устройства, входящие в состав процессора:', 1, 'False')
INSERT INTO Questions (Name, TestId, IsOpenType) VALUES ('Что такое видеокарта?', 1, 'False')
INSERT INTO Questions (Name, TestId, IsOpenType) VALUES ('От чего зависит скорость работы процессора?', 1, 'False')
INSERT INTO Questions (Name, TestId, IsOpenType) VALUES ('Что применяют для подключения компьютера к телефонной сети?', 1, 'False')
INSERT INTO Questions (Name, TestId, IsOpenType) VALUES ('Где хранится выполняемая в данный момент программа и обрабатываемые ею данные?', 1, 'False')
INSERT INTO Questions (Name, TestId, IsOpenType) VALUES ('В каком месте можно сохранить информацию перед отключением компьютера?', 1, 'False')
INSERT INTO Questions (Name, TestId, IsOpenType) VALUES ('Что применяется для долговременного хранения пользовательской информации?', 1, 'False')
INSERT INTO Questions (Name, TestId, IsOpenType) VALUES ('В каком месте нахождения информация будет утеряна при выключении компьютера?', 1, 'False')
INSERT INTO Questions (Name, TestId, IsOpenType) VALUES ('Для чего нужен дисковод?', 1, 'False')
INSERT INTO Questions (Name, TestId, IsOpenType) VALUES ('Устройство, не находящееся в системном блоке:', 1, 'False')
INSERT INTO Questions (Name, TestId, IsOpenType) VALUES ('Устройством визуального воспроизведения символьной и графической информации является:', 1, 'False')
INSERT INTO Questions (Name, TestId, IsOpenType) VALUES ('Какое название имеет система взаимосвязанных технических устройств, которые выполняют ввод, хранение, обработку и вывод информации?', 1, 'False')
INSERT INTO Questions (Name, TestId, IsOpenType) VALUES ('От чего зависит производительность работы компьютера (быстрота выполнения операций)?', 1, 'False')
INSERT INTO Questions (Name, TestId, IsOpenType) VALUES ('Как переводится аббревиатура "ПК"?', 1, 'True')
INSERT INTO Questions (Name, TestId, IsOpenType) VALUES ('Один килобайт равен … байтам', 1, 'True')
INSERT INTO Questions (Name, TestId, IsOpenType) VALUES ('Thread - это:', 2, 'False')
INSERT INTO Questions (Name, TestId, IsOpenType) VALUES ('Блок finaly выполнится в любом случае, кроме ситуации, когда...', 2, 'False')
INSERT INTO Questions (Name, TestId, IsOpenType) VALUES ('Дайте определение унарному оператору', 2, 'False')
INSERT INTO Questions (Name, TestId, IsOpenType) VALUES ('Конструктор - это:', 2, 'False')
INSERT INTO Questions (Name, TestId, IsOpenType) VALUES ('Ограничения типов  определяются с помощью контекстно-зависимого ключевого слова:', 2, 'False')
INSERT INTO Questions (Name, TestId, IsOpenType) VALUES ('Ограничение where T : class указывает , что указатель места заполнения типа Т должен быть:', 2, 'False')
INSERT INTO Questions (Name, TestId, IsOpenType) VALUES ('С помощью какой операции можно получить текущее время и дату?', 2, 'False')
INSERT INTO Questions (Name, TestId, IsOpenType) VALUES ('Выберите правильный вариант создания структуры:', 2, 'False')
INSERT INTO Questions (Name, TestId, IsOpenType) VALUES ('Что из перечисленного ниже является конструктором по умолчанию класса MyClass?', 2, 'False')
INSERT INTO Questions (Name, TestId, IsOpenType) VALUES ('Структуры не могут содержать члены с модификаторами доступа:', 2, 'False')
INSERT INTO Questions (Name, TestId, IsOpenType) VALUES ('О чём говорит модификатор доступа protected?', 2, 'False')
INSERT INTO Questions (Name, TestId, IsOpenType) VALUES ('Модификаторы доступа – это:', 2, 'False')
INSERT INTO Questions (Name, TestId, IsOpenType) VALUES ('DownCast – это:', 2, 'False')
INSERT INTO Questions (Name, TestId, IsOpenType) VALUES ('Какие уровни доступности присутствуют в C#?', 2, 'False')
INSERT INTO Questions (Name, TestId, IsOpenType) VALUES ('Экземпляр класса - это:', 2, 'False')
INSERT INTO Questions (Name, TestId, IsOpenType) VALUES ('Что из перечисленного ниже является пользовательским конструктором класса MyClass?', 2, 'False')
INSERT INTO Questions (Name, TestId, IsOpenType) VALUES ('Что собой подразумевает понятие «инстанцирование»?', 2, 'False')
INSERT INTO Questions (Name, TestId, IsOpenType) VALUES ('Обработка исключительных ситуаций (ExceptionHandling) – это:', 2, 'False')
INSERT INTO Questions (Name, TestId, IsOpenType) VALUES ('Все классы пользовательских исключений должны быть производными от встроенного в С# класса:', 2, 'True')
INSERT INTO Questions (Name, TestId, IsOpenType) VALUES ('Основу обработки исключительных ситуаций в С# составляют ключевые слова:', 2, 'False')
INSERT INTO Questions (Name, TestId, IsOpenType) VALUES ('Метод расширения – это:', 2, 'False')
INSERT INTO Questions (Name, TestId, IsOpenType) VALUES ('Тип данных, который используется по умолчанию как тип значения для перечисления:', 2, 'False')
INSERT INTO Questions (Name, TestId, IsOpenType) VALUES ('Какой тип данных нельзя использовать как тип значения для  перечисления?', 2, 'False')
INSERT INTO Questions (Name, TestId, IsOpenType) VALUES ('С помощью какой команды возможно организовать задержку окна консоли?', 2, 'False')
INSERT INTO Questions (Name, TestId, IsOpenType) VALUES ('Как называется программа, которая преобразовывает исходный код в машинный код?', 2, 'False')
INSERT INTO Questions (Name, TestId, IsOpenType) VALUES ('Как называется набор действий при помощи которых некрасивый, плохо написанный код приводится к стилистически правильному виду?', 2, 'False')
INSERT INTO Questions (Name, TestId, IsOpenType) VALUES ('Каких олимпийских видов спорта больше?', 3, 'False')
INSERT INTO Questions (Name, TestId, IsOpenType) VALUES ('К какому виду спорта относится ВМХ?', 3, 'False')
INSERT INTO Questions (Name, TestId, IsOpenType) VALUES ('Какой вид спорта включили в программу Олимпийских игр в 1990 году?', 3, 'False')
INSERT INTO Questions (Name, TestId, IsOpenType) VALUES ('Сколько лыжных видов спорта входит в Зимние Олимпийские игры?', 3, 'False')
INSERT INTO Questions (Name, TestId, IsOpenType) VALUES ('Как называется вид конькобежного спорта, когда несколько спортсменов катаются по овальной ледовой дорожке длиной 111,12 метра?', 3, 'False')
INSERT INTO Questions (Name, TestId, IsOpenType) VALUES ('Укажите вид спорта, самым титулованным спортсменом которого является является итальянец Эдоардо Манджаротти?', 3, 'False')
INSERT INTO Questions (Name, TestId, IsOpenType) VALUES ('В каком виде спорта за всю историю было разыграно 32 комплекта наград, 28 из которых принадлежат китайцам?', 3, 'False')
INSERT INTO Questions (Name, TestId, IsOpenType) VALUES ('Как называется вид спорта, который включает в себя плавание, велогонку и бег?', 3, 'False')
INSERT INTO Questions (Name, TestId, IsOpenType) VALUES ('С какой периодичностью проводятся Олимпийские игры?', 3, 'False')
INSERT INTO Questions (Name, TestId, IsOpenType) VALUES ('В какой стране проводились Олимпийские игры в 1980 году?', 3, 'True')
INSERT INTO Questions (Name, TestId, IsOpenType) VALUES ('Какая страна считается родиной футбола?', 4, 'False')
INSERT INTO Questions (Name, TestId, IsOpenType) VALUES ('Где был сыгран первый Кубок мира ФИФА?', 4, 'False')
INSERT INTO Questions (Name, TestId, IsOpenType) VALUES ('Если игрок забивает в свои ворота, этот гол называется?', 4, 'True')
INSERT INTO Questions (Name, TestId, IsOpenType) VALUES ('Сколько игроков одновременно находится на поле с обеих сторон?', 4, 'False')
INSERT INTO Questions (Name, TestId, IsOpenType) VALUES ('Какая страна чаще всего и сколько раз выигрывала чемпионат мира?', 4, 'False')
INSERT INTO Questions (Name, TestId, IsOpenType) VALUES ('Если игрок за матч забил 3 мяча, то он оформил?', 4, 'False')
INSERT INTO Questions (Name, TestId, IsOpenType) VALUES ('Как называется наивысшая индивидуальная награда для футболистов?', 4, 'False')
INSERT INTO Questions (Name, TestId, IsOpenType) VALUES ('Какой клуб в XX ст. 5 раз подряд побеждал в Лиге Чемпионов?', 4, 'False')
INSERT INTO Questions (Name, TestId, IsOpenType) VALUES ('Кто выиграл Кубок Мира ФИФА в 2018 году?', 4, 'False')
INSERT INTO Questions (Name, TestId, IsOpenType) VALUES ('Лучшим бомбардиром в истории сборной Португалии является?', 4, 'False')
INSERT INTO Questions (Name, TestId, IsOpenType) VALUES ('Столицей Франции является город', 5, 'False')
INSERT INTO Questions (Name, TestId, IsOpenType) VALUES ('Столицей США является город', 5, 'False')
INSERT INTO Questions (Name, TestId, IsOpenType) VALUES ('Столицей Южной Кореи является город', 5, 'False')
INSERT INTO Questions (Name, TestId, IsOpenType) VALUES ('Столицей Турции является город', 5, 'False')
INSERT INTO Questions (Name, TestId, IsOpenType) VALUES ('Столицей Сирии является город', 5, 'False')
INSERT INTO Questions (Name, TestId, IsOpenType) VALUES ('Столицей Канады является город', 5, 'False')
INSERT INTO Questions (Name, TestId, IsOpenType) VALUES ('Столицей Багамских островов является город', 5, 'False')
INSERT INTO Questions (Name, TestId, IsOpenType) VALUES ('Столицей Бразилии является город', 5, 'False')
INSERT INTO Questions (Name, TestId, IsOpenType) VALUES ('Столицей Алжира является город', 5, 'False')
INSERT INTO Questions (Name, TestId, IsOpenType) VALUES ('Столицей Новой Зеландии является город', 5, 'False')
INSERT INTO Questions (Name, TestId, IsOpenType) VALUES ('Столицей Нигерии является город', 5, 'False')
INSERT INTO Questions (Name, TestId, IsOpenType) VALUES ('Столицей Чили является город', 5, 'False')
INSERT INTO Questions (Name, TestId, IsOpenType) VALUES ('Столицей Уругвая является город', 5, 'False')
INSERT INTO Questions (Name, TestId, IsOpenType) VALUES ('Столицей Мексики является город', 5, 'False')
INSERT INTO Questions (Name, TestId, IsOpenType) VALUES ('Столицей Австралии является город', 5, 'False')
INSERT INTO Questions (Name, TestId, IsOpenType) VALUES ('Столицей Пакистана является город', 5, 'False')
INSERT INTO Questions (Name, TestId, IsOpenType) VALUES ('Столицей Кипра является город', 5, 'False')
INSERT INTO Questions (Name, TestId, IsOpenType) VALUES ('Столицей ОАЭ является город', 5, 'False')
INSERT INTO Questions (Name, TestId, IsOpenType) VALUES ('Столицей Казахстана является город', 5, 'False')
INSERT INTO Questions (Name, TestId, IsOpenType) VALUES ('Столицей Польши является город', 5, 'True')
INSERT INTO Questions (Name, TestId, IsOpenType) VALUES ('Столицей Мадагаскара является город', 5, 'True')
INSERT INTO Questions (Name, TestId, IsOpenType) VALUES ('Столицей Португалии является город', 5, 'True')
INSERT INTO Questions (Name, TestId, IsOpenType) VALUES ('Какого числа началась Великая Отечественная война?', 6, 'False')
INSERT INTO Questions (Name, TestId, IsOpenType) VALUES ('Какая из крепостей прославилась героической обороной в начале войны и надписью "Я умираю, но не сдаюсь! Прощай, Родина" сделанной в казармах войск НКВД СССР?', 6, 'False')
INSERT INTO Questions (Name, TestId, IsOpenType) VALUES ('Были ли достигнуты основный цели плана "Барбаросса"?', 6, 'False')
INSERT INTO Questions (Name, TestId, IsOpenType) VALUES ('Какой из котлов Великой Отечественной войны был крупнейшим в истории?', 6, 'False')
INSERT INTO Questions (Name, TestId, IsOpenType) VALUES ('В честь какого из дворцово-парковых ансамблей получил название плацдарм на берегах Финского залива, который внёс значительный вклад в оборону Ленинграда?', 6, 'False')
INSERT INTO Questions (Name, TestId, IsOpenType) VALUES ('Сколько дней длилась блокада Ленинграда?', 6, 'False')
INSERT INTO Questions (Name, TestId, IsOpenType) VALUES ('Когда завершилась битва за Москву?', 6, 'False')
INSERT INTO Questions (Name, TestId, IsOpenType) VALUES ('Какое мероприятие, направленное на подержание боевого духа, было проведено в столице 7 ноября в ходе Битвы за Москву?', 6, 'False')
INSERT INTO Questions (Name, TestId, IsOpenType) VALUES ('Какой порядковый номер носил приказ советского командования, запрещавший отход войск без приказа? Он вводил формирование штрафных частей и получил название "Ни шагу назад!"', 6, 'False')
INSERT INTO Questions (Name, TestId, IsOpenType) VALUES ('Какое сражение 1942 года считается переломным и связывается с моментом перехвата стратегической инициативы советским командованием?', 6, 'False')
INSERT INTO Questions (Name, TestId, IsOpenType) VALUES ('Где произошла первая за годы великой отечественной войны конференция лидеров трёх ключевых антигитлеровской коалиции СССР, США и Англии?', 6, 'True')
INSERT INTO Questions (Name, TestId, IsOpenType) VALUES ('В честь кого из полководцев войны 1812 года получила Белорусская наступательная операция 1944 года?', 6, 'False')
INSERT INTO Questions (Name, TestId, IsOpenType) VALUES ('На какой из конференций лидеры США, СССР и Англии решали вопрос о послевоенном устройстве мира?', 6, 'False')
INSERT INTO Questions (Name, TestId, IsOpenType) VALUES ('Какая из операций 1945 года стала последней в Великой Отечественной войне?', 6, 'False')
INSERT INTO Questions (Name, TestId, IsOpenType) VALUES ('Какое название было у плана немцев по захвату Москвы?', 6, 'True')

INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Устройство для обработки аналоговых сигналов', 1, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Электронное вычислительное устройство для обработки чисел', 1, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Многофункциональное электронное устройство для работы с информацией', 1, 1)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Устройство для хранения информации любого вида', 1, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Ввода информации', 2, 1)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Для подключения принтера к компьютеру', 2, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Долговременного хранения информации', 2, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Модуляции и демодуляции', 2, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Считывания информации', 2, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Энергонезависимость оперативной памяти', 3, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Наличие номера у каждой ячейки оперативной памяти и возможность доступа к ней', 3, 1)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Возможность хранения программ и данных', 3, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Модули памяти', 4, 1)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Микрочипы', 4, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Двоичный код длиной 8 знаков', 4, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Устройство хранения информации символьного типа', 5, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Устройство вывода информации', 5, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Устройство ввода символьной информации', 5, 1)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Устройство ввода манипуляторного типа', 5, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Арифметико-логическое устройство, устройство управления, регистры', 6, 1)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Дисплейный процессор, видеоадаптер', 6, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Сканер, ПЗУ', 6, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Кэш-память, видеопамять', 6, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Оперативное запоминающее устройство, принтер', 6, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Устройство вывода информации', 7, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Устройство распознавания текстовой информации', 7, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Микросхема, осуществляющая вывод информации на экран', 7, 1)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Устройство ввода информации', 7, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Наличия или отсутствия подключенного принтера', 8, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Тактовой частоты', 8, 1)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Объёма внешнего запоминающего устройства', 8, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Организации интерфейса операционной системы', 8, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Объёма обрабатываемой информации', 8, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Модем', 9, 1)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Сканер', 9, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Факс', 9, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Принтер', 9, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Плоттер', 9, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('На устройстве ввода', 10, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('В процессоре', 10, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('В оперативной памяти', 10, 1)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Во внешней памяти', 10, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('В регистрах процессора', 11, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Во внешней памяти', 11, 1)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('В оперативной памяти', 11, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('На дисководе', 11, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Оперативная память', 12, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Дисковод', 12, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Процессор', 12, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Внешняя память', 12, 1)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('В оперативной памяти', 13, 1)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('На жестком диске', 13, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('На гибком диске', 13, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('На CD-ROM диске', 13, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Обработки команд исполняемой программы', 14, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Долговременного хранения информации', 14, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Хранения команд исполняемой программы', 14, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Чтения/записи данных с внешнего носителя', 14, 1)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Сетевая карта', 15, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Видеокарта', 15, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Процессор', 15, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Сканер', 15, 1)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Жёсткий диск', 15, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Монитор', 16, 1)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Сканер', 16, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Клавиатура', 16, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Процессор', 16, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Системное обеспечение', 17, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Аппаратное обеспечение', 17, 1)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Компьютерное обеспечение', 17, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Программное обеспечение', 17, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Размера экрана монитора', 18, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Быстроты нажатия на клавиши', 18, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Объёма обрабатываемой информации', 18, 1)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Тактовый частоты процессора', 18, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Персональный компьютер', 19, 1)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('1024', 20, 1)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Программа в памяти', 21, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Ссылка на объект', 21, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Элементарная единица исполнения, которую можно планировать  средствами операционной системы', 21, 1)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Значение в стеке', 21, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('В блоке try сгенерируется исключение типа OutOfMemoryException', 22, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('В блоке try сгенерируется исключение типа ArythmeticException', 22, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('В блоке try сгенерируется исключение типа DivideByZeroException', 22, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('В блоке try сгенерируется исключение типа StackOverflowException', 22, 1)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Унарный оператор - оператор, не принимающий параметров', 23, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Унарный оператор - оператор, возвращающий булево значение', 23, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Унарный оператор - оператор, принимающий один параметр', 23, 1)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Унарный оператор - оператор, принимающий два параметра', 23, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Некоторая сущность, обладающая определенным состоянием и поведением', 24, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Специальный блок инструкций, вызываемый при создании объекта', 24, 1)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Способ доступа к внутреннему состоянию объекта', 24, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Описание конкретного объекта в памяти', 24, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Throw', 25, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Default', 25, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Volatile', 25, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Where', 25, 1)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Производным от указанного базового класса', 26, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Структурного типа, кроме Nullable', 26, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Ссылочного типа; это также распространяется на тип любого класса, интерфейса, делегата или массива', 26, 1)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Запись не корректная', 26, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('DateTime date = DateTime.GetCurrent();', 27, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('DateTime date = new DateTime();', 27, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('DateTime date = DateTime.Now();', 27, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('DateTime date = DateTime.Now;', 27, 1)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('sealed struct MyStruct {}  ', 28, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('struct MyStruct {}', 28, 1)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('virtual struct MyStruct {}', 28, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('abstract struct MyStruct {}', 28, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('public void MyClass(){}', 29, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('public MyClass(){}', 29, 1)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('public int Constructor(){}', 29, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('public MyClass(string s){}', 29, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('internal', 30, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('public', 30, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('private', 30, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('protected', 30, 1)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Доступ к типу или элементу можно получить только из кода в том же классе или структуре, либо в производном классе', 31, 1)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Доступ к типу или члену возможен из любого другого кода в той же сборке или другой сборке, ссылающейся на него', 31, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Доступ ограничен текущей сборкой или типами, которые являются производными от содержащего класса', 31, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Доступ к типу или члену возможен из любого кода в той же сборке, но не из другой сборки', 31, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Не используются в C#', 32, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Ключевые слова, задающие максимальное количество полей класса', 32, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Параметры пользовательского конструктора класса', 32, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Ключевые слова, задающие объявленную доступность члена или типа', 32, 1)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Преобразование класса в изолированный класс', 33, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Приведение экземпляра производного класса к базовому типу', 33, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Операция уменьшения значения операнда на 1', 33, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Приведение экземпляра базового типа к производному типу', 33, 1)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('public, private, protected internal, protected, internal', 34, 1)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('public, private, protected, external', 34, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('public, private, protected, internal', 34, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('public, private, protected external, protected, external', 34, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Некоторая сущность, обладающая определенным состоянием и поведением', 35, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Способ доступа к внутреннему состоянию объекта', 35, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Специальный блок инструкций, вызываемый при создании объекта', 35, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Описание конкретного объекта в памяти', 35, 1)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('public MyClass(string s){}', 36, 1)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('public int Constructor(){}', 36, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('public void MyClass(){}', 36, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('public MyClass(){}', 36, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Cпособ доступа к внутреннему состоянию объекта', 37, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Сокрытие реализации', 37, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Приведение от производного типа к базовому', 37, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Создание экземпляра класса ', 37, 1)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Механизм, предназначенный для описания процесса выполнения программы', 38, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Механизм для определения ошибок', 38, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Механизм, предназначенный для описания реакции программы на ошибки', 38, 1)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Механизм, предназначенный для предотвращения ошибок в приложении', 38, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Exception', 39, 1)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('try и foreach', 40, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('catch и finally', 40, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('try и finally', 40, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('try и catch', 40, 1)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Статический метод ровно с одним параметром', 41, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Произвольный метод, но его единственный параметр объявлен с модификатором this', 41, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Статический метод без параметров', 41, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Статический метод в статическом классе, но его первый параметр определяет, с каким типом оперирует метод, и перед параметром идет модификатор this', 41, 1)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('int', 42, 1)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('short', 42, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('float', 42, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('byte', 42, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('short', 43, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('float', 43, 1)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('byte', 43, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('int', 43, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Console.WriteLine();', 44, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Console.Beep();', 44, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Console.WriteKey();', 44, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Console.ReadKey();', 44, 1)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Ретранслятор', 45, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('IDE', 45, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Компилятор', 45, 1)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Visual Studio', 45, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Редизайн', 46, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Составление алгоритма', 46, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Рефакторинг', 46, 1)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Псевдокод', 46, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Одинаковое количество', 47, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Летних', 47, 1)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Зимних', 47, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Конный спорт', 48, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Водные виды спорта', 48, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Велоспорт', 48, 1)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Перетягивание каната', 49, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Лакросс', 49, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Крикет', 49, 1)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('3', 50, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('6', 50, 1)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('8', 50, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Роке', 51, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Фристайл', 51, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Шорт-трек', 51, 1)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Фехтование', 52, 1)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Бобслей', 52, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Стрельба из лука', 52, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Триатлон', 53, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Дзюдо', 53, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Настольный теннис', 53, 1)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Триатлон', 54, 1)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Биатлон', 54, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Лёгкая атлетика', 54, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('1 раз в 3 года', 55, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('1 раз в 6 лет', 55, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('1 раз в 4 года', 55, 1)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Ежегодно', 55, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Россия', 56, 1)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Франция', 57, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Аргентина', 57, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Англия', 57, 1)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Испания', 57, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Уругвай', 58, 1)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Бразилия', 58, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Россия', 58, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Англия', 58, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Автогол', 59, 1)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('22', 60, 1)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('21', 60, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('11', 60, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('20', 60, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Англия (5 раз)', 61, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Бразилия (5 раз)', 61, 1)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Аргентина (3 раза)', 61, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Испания (4 раза)', 61, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Пента-трик', 62, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Дубль', 62, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Хет-трик', 62, 1)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Золотой мяч', 63, 1)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Серебряный кубок', 63, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Золотая бутса', 63, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Барселона', 64, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Реал Мадрид', 64, 1)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Севилья', 64, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Ливерпуль', 64, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Франция', 65, 1)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Португалия', 65, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Испания', 65, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Бразилия', 65, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Пепе', 66, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Месси', 66, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Роналду', 66, 1)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Кварежма', 66, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Брюссель', 67, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Париж', 67, 1)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Мадрид', 67, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Голливуд', 68, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Вашингтон', 68, 1)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Нью-Йорк', 68, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Пхеньян', 69, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Сеул', 69, 1)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Тайбей', 69, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Анталия', 70, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Анкара', 70, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Стамбул', 70, 1)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Дамаск', 71, 1)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Алеппо', 71, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Бейрут', 71, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Квебек', 72, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Оттава', 72, 1)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Монреаль', 72, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Кингстон', 73, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Каракас', 73, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Нассау', 73, 1)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Буэнос-Айрес', 74, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Бразилиа', 74, 1)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Сан-Паулу', 74, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Рабат', 75, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Триполи', 75, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Алжир', 75, 1)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Веллингтон', 76, 1)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Хобарт', 76, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Папеэте', 76, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Абуджа', 77, 1)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Лагос', 77, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Ниамей', 77, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Чили', 78, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Сантьяго', 78, 1)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Лима', 78, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Уругвай', 79, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Санта-Мария', 79, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Монтевидео', 79, 1)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Акапулько', 80, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Мехико', 80, 1)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Гуадалахара', 80, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Мельбурн', 81, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Сидней', 81, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Канберра', 81, 1)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Исламабад', 82, 1)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Карачи', 82, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Кандагар', 82, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Ларнака', 83, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Никосия', 83, 1)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Лимасол', 83, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Абу-Даби', 84, 1)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Дубай', 84, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Шарджа', 84, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Алматы', 85, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Караганда', 85, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Астана', 85, 1)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Варшава', 86, 1)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Антананариву', 87, 1)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Лиссабон', 88, 1)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('22 июля 1941 года', 89, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('22 июня 1941 года', 89, 1)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('1 сентября 1939 года', 89, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Крепость Осовец', 90, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Гродненская крепость', 90, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Познанская крепость', 90, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Брестская крепость', 90, 1)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Да, Вермахт смог разгромить РККА к концу 1941 года', 91, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Стратегия блицкрига провалилась', 91, 1)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Частично РККА не была разгромлена, но Вермахт смог выиграть"Битву за Москву"', 91, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Минский котёл', 92, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Вяземский котёл', 92, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Киевский котёл', 92, 1)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Франкфуртско-Губенской котёл', 92, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Царское село (Царско сельский плацдарм)', 93, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Ораниенбаум (Ораниенбаумский пятачок)', 93, 1)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Павловск (Павловский выступ)', 93, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('872 дня', 94, 1)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('653 дня', 94, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('412 дня', 94, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('123 дня', 94, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('27 января 1944', 95, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('23 августа 1943', 95, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('20 апреля 1942 года', 95, 1)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('30 сентября 1941 года', 95, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('22 июня 1941 года', 95, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Парад на Красной площади', 96, 1)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Праздничное шествие в честь Ленина', 96, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Марш пленных немцев по Москве', 96, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('XVIII съезд ВКП(б)', 96, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Приказ № 270', 97, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Приказ № 227', 97, 1)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Приказ № 137', 97, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Приказ № 53', 97, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Мурманская наступательная операция', 98, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Сталинградская битва', 98, 1)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Курская битва', 98, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Операция "Искра"', 98, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Тегеран', 99, 1)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Михаил Илларионович Голенищев-Кутузов-Смоленский', 100, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Михаил Богданович Барклай-де-Толли', 100, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Пётр Иванович Багратион', 100, 1)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Пётр Христианович Витгенштейн', 100, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Тегеранская конференция', 101, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Ялтинская конференция', 101, 1)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Потсдамская конференция', 101, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Московская конференция', 101, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Берлинская наступательная операция', 102, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Висло-Одерская операция', 102, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Восточно-Померанская операция', 102, 0)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Пражская операция', 102, 1)
INSERT INTO [dbo].[Answers] ([Name], [QuestionId], [IsCorrect]) VALUES ('Тайфун', 103, 1)

INSERT INTO [dbo].[Results] ([Point], [UserName], [IsSuccess], [TestId]) VALUES (100, 'Тимофеев Владимир Иванович', 1, 1)
INSERT INTO [dbo].[Results] ([Point], [UserName], [IsSuccess], [TestId]) VALUES (96.2, 'Иванов Иван Иванович', 1, 2)
INSERT INTO [dbo].[Results] ([Point], [UserName], [IsSuccess], [TestId]) VALUES (100, 'Тимофеев Владимир Иванович', 1, 2)
INSERT INTO [dbo].[Results] ([Point], [UserName], [IsSuccess], [TestId]) VALUES (96.2, 'Тимофеев Владимир Иванович', 1, 2)
INSERT INTO [dbo].[Results] ([Point], [UserName], [IsSuccess], [TestId]) VALUES (88.5, 'Сидоров Андрей Семёнович', 1, 2)
INSERT INTO [dbo].[Results] ([Point], [UserName], [IsSuccess], [TestId]) VALUES (86.4, 'Сидоров Андрей Семёнович', 1, 5)
INSERT INTO [dbo].[Results] ([Point], [UserName], [IsSuccess], [TestId]) VALUES (50, 'Сидоров Андрей Семёнович', 0, 5)
INSERT INTO [dbo].[Results] ([Point], [UserName], [IsSuccess], [TestId]) VALUES (81.8, 'Иванов Иван Иванович', 1, 5)
INSERT INTO [dbo].[Results] ([Point], [UserName], [IsSuccess], [TestId]) VALUES (77.3, 'Иванов Иван Иванович', 1, 5)